 name: Build Reusable
 on:
   workflow_call: #被呼叫
     inputs:
       version: aaa
         required: true
         type: string
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       -run: echo "Building version ${{ inputs.version}}"

